import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { PIPELINE_STAGES, STAGE_LABELS, type PipelineStage, type WorkerStatusSnapshot } from "./observability.js";
import "./styles.css";

const apiBase = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8787";
let adminKey: string | null = null;
type WatchedChannel = { broadcaster_id: string; login: string; display_name: string; enabled: number | boolean; auto_process: number | boolean; profile_id: string; last_vod_id: string | null; eventsub_subscription_id: string | null };
type Vod = { channel: string; vodId: string; title: string; durationSeconds: number; createdAt?: string };
type EventSubStatus = { configured: boolean; type: string };
type Job = { jobId: string; vodId?: string; status: string; stage: string; progress: number | null; message?: string | null; elapsedMs?: number | null; etaMs?: number | null; error?: string | null; worker?: string | null; updatedAt?: string | null; clipsPlanned?: number | null; clipsRendered?: number | null };
async function api<T>(path: string, init?: RequestInit): Promise<T> { if (!adminKey) adminKey = window.prompt("Enter the Auto Clipper admin key")?.trim() || null; if (!adminKey) throw new Error("Admin key required."); let response: Response; try { const headers = new Headers(init?.headers); headers.set("Authorization", `Bearer ${adminKey}`); response = await fetch(`${apiBase}${path}`, { ...init, headers }); } catch { throw new Error("Cannot reach API. Check Cloudflare deployment / API URL."); } const body = await response.json().catch(() => ({})) as { status?: string; message?: string; data?: T }; if (response.status === 401) { adminKey = null; throw new Error("Admin key rejected. Retry the action to enter it again."); } if (!response.ok || body.status !== "ok") throw new Error(body.message ?? `API returned HTTP ${response.status}.`); return body.data as T; }
const listChannels = () => api<WatchedChannel[]>("/api/channels");
const addChannel = (channel: string) => api<unknown>("/api/channels", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel }) });
const updateChannel = (id: string, body: Record<string, unknown>) => api<unknown>(`/api/channels/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
const removeChannel = (id: string) => api<unknown>(`/api/channels/${id}`, { method: "DELETE" });
const listVods = (channel: string) => api<Vod[]>(`/api/vods?channel=${encodeURIComponent(channel)}&limit=20`);
const createJob = (vodId: string) => api<Job>("/api/jobs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ vodId }) });
const listJobs = () => api<Job[]>("/api/jobs");
const getWorker = () => api<WorkerStatusSnapshot>("/api/worker/status");
const getEventSubStatus = () => api<EventSubStatus>("/api/eventsub/status");

function App() {
  const [route, setRoute] = useState(window.location.hash.slice(1) || "dashboard"); const [channels, setChannels] = useState<WatchedChannel[]>([]); const [vods, setVods] = useState<Vod[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [worker, setWorker] = useState<WorkerStatusSnapshot | null>(null); const [eventSub, setEventSub] = useState<EventSubStatus | null>(null); const [message, setMessage] = useState("Ready"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { const onHash = () => setRoute(window.location.hash.slice(1) || "dashboard"); window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash); }, []);
  const refresh = () => Promise.all([listChannels(), listJobs(), getWorker(), getEventSubStatus()]).then(([c, j, w, e]) => { setChannels(c); setJobs(j); setWorker(w); setEventSub(e); });
  useEffect(() => { refresh().catch((e) => setError(e.message)); }, []);
  useEffect(() => { const timer = window.setInterval(() => refresh().catch(() => undefined), jobs.some((job) => ["QUEUED", "CLAIMED", "RUNNING", "queued", "running"].includes(job.status)) ? 3000 : 15000); return () => window.clearInterval(timer); }, [jobs]);
  async function run(action: () => Promise<void>, success: string) { setBusy(true); setError(""); try { await action(); setMessage(success); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); } }
  async function loadVods(channel: string) { await run(async () => setVods(await listVods(channel)), "VODs loaded"); window.location.hash = "vods"; }
  async function process(vodId: string) { await run(async () => { await createJob(vodId); await refresh(); window.location.hash = "jobs"; }, "Queued for local worker"); }
  const watching = useMemo(() => channels.filter((c) => Boolean(c.enabled)).length, [channels]);
  const queued = jobs.filter((job) => ["QUEUED", "CLAIMED", "queued"].includes(job.status)).length;
  const running = jobs.filter((job) => ["RUNNING", "running"].includes(job.status)).length;
  const clips = jobs.reduce((sum, job) => sum + (job.clipsRendered ?? 0), 0);
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brandMark">A</span><span>Auto-Clipper</span></div><nav aria-label="Primary navigation">{[["dashboard", "▦", "Dashboard"], ["channels", "◉", "Channels"], ["vods", "▶", "VODs"], ["jobs", "◷", "Jobs"], ["clips", "✂", "Clips"]].map(([id, icon, label]) => <a className={`navItem ${route === id ? "active" : ""}`} href={`#${id}`} key={id}>{icon} <span>{label}</span></a>)}</nav><WorkerIndicator worker={worker} compact /></aside><section className="appMain"><header className="topbar"><div><p className="eyebrow">WORKSPACE / {route.toUpperCase()}</p><h1>Auto Clipper</h1></div><div className="topbarRight"><WorkerIndicator worker={worker} /><span className="livePill">{message}</span><span className="avatar">AC</span></div></header><section className="workspace">{error && <p className="errorBanner" role="alert">{error}</p>}{route === "channels" ? <ChannelsPage channels={channels} eventSub={eventSub} busy={busy} onAdd={(name) => run(async () => { await addChannel(name); setChannels(await listChannels()); }, "Channel saved")} onUpdate={(id, body) => run(async () => { await updateChannel(id, body); setChannels(await listChannels()); }, "Channel updated")} onRemove={(id) => run(async () => { await removeChannel(id); setChannels(channels.filter((c) => c.broadcaster_id !== id)); }, "Channel removed")} onVods={loadVods} /> : route === "vods" ? <VodsPage vods={vods} onProcess={process} /> : route === "jobs" ? <JobsPage jobs={jobs} worker={worker} /> : route === "clips" ? <ClipsPage jobs={jobs} /> : <DashboardPage channels={channels} watching={watching} queued={queued} running={running} clips={clips} onVods={loadVods} />}</section></section></main>;
}

function WorkerIndicator({ worker, compact = false }: { worker: WorkerStatusSnapshot | null; compact?: boolean }) { const label = !worker ? "LOCAL PC UNKNOWN" : worker.online ? "LOCAL PC ONLINE" : "LOCAL PC OFFLINE"; const seen = worker?.lastSeenAt ? `Last seen ${relativeTime(worker.lastSeenAt)}` : "No heartbeat yet"; return <span className={`workerIndicator ${worker?.online ? "online" : worker ? "offline" : "unknown"}`} title={seen}><span className="statusDot" />{compact ? <><strong>{label}</strong><small>{seen}</small></> : <>{label}<small>{seen}</small></>}</span>; }
function JobsPage({ jobs, worker }: { jobs: Job[]; worker: WorkerStatusSnapshot | null }) { return <><div className="pageIntro"><div><h2>Jobs</h2><p>Cloud state refreshes every 3 seconds while work is active.</p></div><span className="versionTag">{worker?.online ? "LOCAL WORKER ONLINE" : "LOCAL WORKER OFFLINE"}</span></div><section className="panel workerGuide"><div><span className="eyebrow">ON YOUR COMPUTER</span><h2>Start Local Worker</h2><p>Browser queues work. Local worker downloads, analyzes, renders, and reports compact state here.</p><p>Optional cue detection: install local Whisper, then set <code>WHISPER_MODEL=base</code>.</p></div><pre>$env:AUTO_CLIPPER_API_BASE_URL="https://auto-video-clip-api.dharzannn.workers.dev"{`\n`}$env:AUTO_CLIPPER_WORKER_TOKEN="YOUR_TOKEN"{`\n`}$env:WHISPER_MODEL="base"{`\n`}npm run build{`\n`}npm run local:worker{`\n\n`}Status: npm run local:status{`\n`}Monitor: npm run local:monitor</pre></section><div className="jobList">{jobs.length ? jobs.map((job) => <JobCard key={job.jobId} job={job} worker={worker} />) : <div className="empty panel"><h2>No jobs yet.</h2><p>Choose a VOD and click Process Locally.</p></div>}</div></>; }
function JobCard({ job, worker }: { job: Job; worker: WorkerStatusSnapshot | null }) { const status = job.status.toUpperCase(); const stage = normalizeStage(job.stage); const queuedOffline = status === "QUEUED" && !worker?.online; const stale = status === "RUNNING" && job.updatedAt != null && Date.now() - Date.parse(job.updatedAt.replace(" ", "T") + (job.updatedAt.includes("Z") ? "" : "Z")) > 180000; return <article className={`panel jobCard ${status.toLowerCase()}`}><div className="jobSummary"><div><h2>{job.vodId ? `VOD ${job.vodId}` : job.jobId}</h2><p><strong className={`jobStatus ${status.toLowerCase()}`}>{status}</strong> · {job.worker ? `Worker: ${job.worker}` : "Worker: waiting"}</p>{queuedOffline && <p className="jobNotice">Waiting for local worker. Your job is safely queued.<br />Start: <code>npm run local:worker</code></p>}{stale && <p className="jobNotice warning">Worker may be stalled. Last update {relativeTime(job.updatedAt)}.</p>}{status === "FAILED" && <p className="jobError">Failed stage: {stageLabel(stage)}<br />Error: {job.error ?? "UNKNOWN"}</p>}{status === "COMPLETE" && <p className="jobComplete">Clips rendered: {job.clipsRendered ?? job.clipsPlanned ?? 0}</p>}</div><div className="jobPercent">{job.progress == null ? "—" : `${Math.round(job.progress * 100)}%`}</div></div><div className="jobMeta"><span>Stage<br /><strong>{stageLabel(stage)}</strong></span><span>Elapsed<br /><strong>{formatDuration(job.elapsedMs)}</strong></span><span>Last update<br /><strong>{relativeTime(job.updatedAt)}</strong></span><span>ETA<br /><strong>{job.etaMs == null ? "—" : formatDuration(job.etaMs)}</strong></span></div><div className="progressTrack"><span style={{ width: `${Math.max(0, Math.min(1, job.progress ?? 0)) * 100}%` }} /></div><StageTimeline job={job} /></article>; }
function StageTimeline({ job }: { job: Job }) { const status = job.status.toUpperCase(); const current = normalizeStage(job.stage); const index = PIPELINE_STAGES.indexOf(current); return <div className="timeline">{PIPELINE_STAGES.map((stage, position) => { const state = status === "COMPLETE" || (position < index && status !== "QUEUED") ? "complete" : stage === current && status === "FAILED" ? "failed" : stage === current && status === "RUNNING" ? "running" : "pending"; return <span className={`timelineStage ${state}`} key={stage}><b>{state === "complete" ? "✓" : state === "running" ? "▶" : state === "failed" ? "✕" : "○"}</b>{STAGE_LABELS[stage]}{state === "running" ? ` ${Math.round((job.progress ?? 0) * 100)}%` : ""}</span>; })}</div>; }
function ClipsPage({ jobs }: { jobs: Job[] }) { const complete = jobs.filter((job) => job.status.toUpperCase() === "COMPLETE"); return <><div className="pageIntro"><div><h2>Clips</h2><p>Completed exports stay on your local PC.</p></div></div>{complete.length ? <div className="vodCards">{complete.map((job) => <article className="panel vodCard" key={job.jobId}><div><h2>{job.vodId ? `VOD ${job.vodId}` : job.jobId}</h2><p>{job.clipsRendered ?? job.clipsPlanned ?? 0} clips ready · local files only</p></div><code>work/{job.jobId}/exports/</code><span className="state saved">READY ON PC</span></article>)}</div> : <div className="empty panel"><h2>No clips exported yet.</h2><p>Run a job to generate deterministic local clip exports.</p></div>}</>; }
function ChannelsPage(props: { channels: WatchedChannel[]; eventSub: EventSubStatus | null; busy: boolean; onAdd: (name: string) => void; onUpdate: (id: string, body: Record<string, unknown>) => void; onRemove: (id: string) => void; onVods: (channel: string) => void }) { const [name, setName] = useState(""); return <><div className="pageIntro"><div><h2>Watched Channels</h2><p>Add Twitch channels to track future VODs.</p></div><span className="versionTag">{props.eventSub?.configured ? "EVENTSUB READY" : "EVENTSUB NOT CONFIGURED"}</span></div><form className="inputRow" onSubmit={(e) => { e.preventDefault(); if (name.trim()) { props.onAdd(name.trim()); setName(""); } }}><label className="srOnly" htmlFor="channel-input">Twitch username</label><input id="channel-input" placeholder="Twitch username" value={name} onChange={(e) => setName(e.target.value)} /><button disabled={props.busy || !name.trim()}>+ Add Channel</button></form><div className="channelGrid">{props.channels.length ? props.channels.map((channel) => <ChannelCard key={channel.broadcaster_id} channel={channel} {...props} />) : <div className="empty panel"><h2>No watched channels yet.</h2><p>Add a Twitch channel to automatically track future VODs.</p></div>}</div></>; }
function ChannelCard({ channel, onUpdate, onRemove, onVods, busy }: { channel: WatchedChannel; onUpdate: (id: string, body: Record<string, unknown>) => void; onRemove: (id: string) => void; onVods: (channel: string) => void; busy: boolean }) { const enabled = Boolean(channel.enabled); return <article className="panel channelCard"><div className="channelTitle"><div><h2>{channel.display_name}</h2><p>Twitch channel · {channel.login}</p></div><span className={`state ${enabled ? "saved" : "disabled"}`}>{enabled ? "Saved" : "Disabled"}</span></div><dl><dt>Subscription</dt><dd>Not configured</dd><dt>Latest VOD</dt><dd>{channel.last_vod_id ?? "None"}</dd><dt>Auto Process</dt><dd><button className="toggle" disabled={busy} onClick={() => onUpdate(channel.broadcaster_id, { autoProcess: !Boolean(channel.auto_process) })}>{Boolean(channel.auto_process) ? "ON" : "OFF"}</button></dd><dt>Profile</dt><dd>{channel.profile_id === "generic" ? "Generic" : channel.profile_id}</dd><dt>Enabled</dt><dd><button className="toggle secondary" disabled={busy} onClick={() => onUpdate(channel.broadcaster_id, { enabled: !enabled })}>{enabled ? "ON" : "OFF"}</button></dd></dl><div className="cardActions"><button onClick={() => onVods(channel.login)}>View VODs</button><button className="danger" onClick={() => onRemove(channel.broadcaster_id)}>Remove</button></div></article>; }
function DashboardPage({ channels, watching, queued, running, clips, onVods }: { channels: WatchedChannel[]; watching: number; queued: number; running: number; clips: number; onVods: (channel: string) => void }) { return <><div className="pageIntro"><div><h2>Clip workspace</h2><p>Monitor local processing from one shared state.</p></div><span className="versionTag">LIVE STATE</span></div><div className="stats"><Stat label="Watching" value={String(watching)} /><Stat label="Queued" value={String(queued)} /><Stat label="Running" value={String(running)} /><Stat label="Clips" value={String(clips)} /></div><section className="panel"><div className="panelHead"><div><span className="eyebrow">WATCHED CHANNELS</span><h2>Channels</h2></div></div>{channels.length ? channels.map((c) => <div className="summaryRow" key={c.broadcaster_id}><strong>{c.display_name}</strong><span>{Boolean(c.auto_process) ? "Auto Process ON" : "Auto Process OFF"}</span><span>{c.last_vod_id ? `Latest VOD ${c.last_vod_id}` : "No VOD baseline"}</span><button onClick={() => onVods(c.login)}>View VODs</button></div>) : <div className="empty"><p>No watched channels yet.</p><a href="#channels">Add your first channel</a></div>}</section></>; }
function VodsPage({ vods, onProcess }: { vods: Vod[]; onProcess: (id: string) => void }) { return <><div className="pageIntro"><div><h2>Recent VODs</h2><p>Choose VODs for local processing.</p></div></div><div className="vodCards">{vods.length ? vods.map((vod) => <article className="panel vodCard" key={vod.vodId}><div><h2>{vod.title}</h2><p>{vod.channel} · {Math.round(vod.durationSeconds / 60)} min{vod.createdAt ? ` · ${new Date(vod.createdAt).toLocaleDateString()}` : ""}</p></div><code>{vod.vodId}</code><button onClick={() => onProcess(vod.vodId)}>Process Locally</button></article>) : <div className="empty panel"><h2>No VODs loaded yet.</h2><p>Open a watched channel and choose View VODs.</p></div>}</div></>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="stat"><span>{label}</span><strong>{value}</strong></div>; }
function normalizeStage(stage: string): PipelineStage { const found = PIPELINE_STAGES.find((item) => item === stage.toUpperCase()); return found ?? "RESOLVE"; }
function stageLabel(stage: PipelineStage): string { return STAGE_LABELS[stage]; }
function formatDuration(ms: number | null | undefined): string { if (ms == null) return "—"; const seconds = Math.max(0, Math.round(ms / 1000)); return `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`; }
function relativeTime(value: string | null | undefined): string { if (!value) return "never"; const ms = Math.max(0, Date.now() - Date.parse(value.replace(" ", "T") + (value.includes("Z") ? "" : "Z"))); const seconds = Math.round(ms / 1000); return seconds < 60 ? `${seconds} sec ago` : `${Math.round(seconds / 60)}m ago`; }
createRoot(document.getElementById("root")!).render(<App />);
